apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - name: chrome
        image: selenium/standalone-chrome:4.18.1
        ports:
        - containerPort: 4444

