apiVersion: batch/v1
kind: Job
metadata:
  name: test-controller
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: controller
        image: senagumus/testops-insider-selenium:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: SELENIUM_REMOTE_URL
            value: "http://chrome-service:4444"
        command: ["pytest", "-v", "testops"]

